"""rename function to tech_function

Revision ID: 1568568c75df
Revises: b2add4617ad4
Create Date: 2025-05-08 13:08:56.059040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1568568c75df'
down_revision = 'b2add4617ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tech_function', sa.String(), nullable=True))
        batch_op.drop_column('function')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('function', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('tech_function')

    # ### end Alembic commands ###
