"""rename tech_function to description

Revision ID: a3f851a43d36
Revises: 1568568c75df
Create Date: 2025-05-08 13:37:47.525545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f851a43d36'
down_revision = '1568568c75df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.drop_column('tech_function')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tech_function', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
